

# This file was *autogenerated* from the file hybrid.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_0p292 = RealNumber('0.292'); _sage_const_8 = Integer(8); _sage_const_16p4 = RealNumber('16.4'); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3)#example  sage hybrid.sage -n "140:150:10" -q 3329 -eta 3

load("../framework/instance_gen.sage")
load("../batchCVP.py")


import argparse


def entropy(D):
    H = sum( [ -p*log(p,_sage_const_2 ) for p in D.values() ] )
    return H

parser = argparse.ArgumentParser()
parser.add_argument("n", type=str)
parser.add_argument("q", type=int)
parser.add_argument("eta", type=int)

args, unknown = parser.parse_known_args()
if len(unknown) > _sage_const_0 :
    print("Unknown arguments " + str(unknown) + " will be ignored.")

print(args.n)

nMin, nMax, nStep = args.n.split(":")
nMin = int(nMin)
nMax = int(nMax)
nStep = int(nStep)

q = args.q
eta = args.eta

D_s = build_centered_binomial_law(eta)
D_e = D_s

H = entropy(D_s)

costNonHybrid = _sage_const_0 
bestCosts = _sage_const_0 

print("n\tkappa\t\tBKZ only\t\tHybrid")

for n in range(nMin,nMax+_sage_const_1 ,nStep):
    for kappa in range(_sage_const_5 ):
        A, b, dbdd = initialize_from_LWE_instance(DBDD_predict_diag, n-kappa, q, n, D_e, D_s, verbosity = _sage_const_0 )
        dbdd.integrate_q_vectors(q)

        beta, delta = dbdd.estimate_attack()

        costBKZ = _sage_const_0p292 *beta + log(_sage_const_8 *dbdd.dim(), _sage_const_2 ) + _sage_const_16p4 
        _, costCVP = batchCVPP_cost(beta, H*kappa, sqrt(_sage_const_4 /_sage_const_3 ), _sage_const_1 )

        if kappa == _sage_const_0 :
            costNonHybrid = costBKZ
            betaNonHybrid = beta

        if costCVP > costBKZ:
            break

        costHybrid = costBKZ+_sage_const_1 
        betaHybrid = beta

    print("%d\t%d\t\t%d (%f)\t\t%d (%f)" % (n,kappa,betaNonHybrid,costNonHybrid, betaHybrid, costHybrid))

