

# This file was *autogenerated* from the file lwe_histo.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_100p = RealNumber('100.'); _sage_const_20 = Integer(20); _sage_const_0p4 = RealNumber('0.4'); _sage_const_10p5 = RealNumber('10.5')
import numpy as np
import pickle


L = {}

path = "./lwe_instances/reduced_lattices/"
filename = "tph_170_binomial_3.0000_1_91_97.pkl" #fig. 2 (left)
# filename = "tph_170_binomial_3.0000_1_91_93.pkl" #fig. 2 (right)
n_guess_coords = [ int( filename.split("_")[_sage_const_4 ] ) ]
with open(path+filename,"rb") as file:
    L.update( pickle.load(file) )
    
print(len(L))
D = L

AGGR = {}
AGGRT = {}
just_dists = []
walltimes = []
for key in D.keys():
    n, lat_index, n_slicer_coord, n_guess_coord, ex_cntr = key
    walltime =  abs(D[key]['wrong_guess_time_alg3']) + abs(D[key]['wrong_guess_time_alg2']) #D[key]["walltime"]
    dist_bnd = D[key]["dist_bnd"]
    succ = D[key]["succ"]
    fail_reason = D[key]["fail_reason"]
    just_dists.append( dist_bnd )
    if not n_guess_coord in AGGR.keys():
        AGGR[n_guess_coord] = {}
        AGGRT[n_guess_coord] = {}
    if not dist_bnd in AGGR[n_guess_coord].keys():
        AGGR[n_guess_coord][dist_bnd] = [_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 ] #totnum, succ, failparasites, failothers 
        AGGRT[n_guess_coord][dist_bnd] = walltime
    walltimes.append(walltime)
    AGGR[n_guess_coord][dist_bnd][_sage_const_0 ] += _sage_const_1 
    AGGR[n_guess_coord][dist_bnd][_sage_const_1 ] += succ
    if not succ:
        if "par" in fail_reason:
            AGGR[n_guess_coord][dist_bnd][_sage_const_2 ] += _sage_const_1 
        else:
            AGGR[n_guess_coord][dist_bnd][_sage_const_3 ] += _sage_const_1 

for key in AGGR.keys():
    for kkey in AGGR[key]:
        AGGRT[key][kkey] = AGGRT[key][kkey]/AGGR[key][kkey][_sage_const_0 ]
        AGGR[key][kkey] = {
            "succ": AGGR[key][kkey][_sage_const_1 ]/AGGR[key][kkey][_sage_const_0 ],
            "para": AGGR[key][kkey][_sage_const_2 ]/AGGR[key][kkey][_sage_const_0 ],
            "oth": AGGR[key][kkey][_sage_const_3 ]/AGGR[key][kkey][_sage_const_0 ],
        }

for kappa in n_guess_coords: 
    l, r = [], []
    for key in AGGR[kappa]:
        l.append( (key,AGGR[kappa][key]) )
    
    l = sorted( l, key= lambda x: -x[_sage_const_1 ]["succ"] )
    ls, lf_para, lf_oth = [], [], []
    for ll in l:
        if ll[_sage_const_1 ]["succ"]:
            ls.append(ll[_sage_const_0 ])
        else:
            if ll[_sage_const_1 ]["oth"]:
                lf_oth.append(ll[_sage_const_0 ])
            else:
                lf_para.append(ll[_sage_const_0 ])
            
    

    print(f"lf_para, lf_oth, ls: {len(lf_para),len(lf_oth),len(ls)}")
    tot = len(lf_para)+len(lf_oth)+len(ls)
    print( f"sum: {tot}" )
    succpr = (len(ls) / tot)*_sage_const_100p 
    Hs = histogram(ls,bins=_sage_const_20 ,color="green", label=["Succ"], alpha=_sage_const_0p4 , title=f"Hybrid ternary $n$={n}, sli_dim={n_slicer_coord}, kappa={kappa}, x10 nrand , succ={succpr:.01f}%" , figsize=_sage_const_10p5 )
    Hpara = histogram(lf_para,bins=_sage_const_20 ,color="blue", label=["Too short"], alpha=_sage_const_0p4 )
    Hpoth = histogram(lf_oth,bins=_sage_const_20 ,color="red", label=["Fail"], alpha=_sage_const_0p4 )
    Histo = list_plot([(_sage_const_1 ,_sage_const_1 )], color="white")
    if len(ls):
        Histo += Hs
    if len(lf_para):
        Histo += Hpara
    if len(lf_oth):
        Histo += Hpoth
    Histo.save_image( f"h{n}_{kappa}.png" )

