"""
Examples:
sage hybrid_cost kyber208 -kmax=32
sage hybrid_cost kyber1024 -kmax=60
"""


# This file was *autogenerated* from the file ./hybrid_estimator/hybrid_cost.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_50 = Integer(50); _sage_const_513 = Integer(513); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0p5 = RealNumber('0.5'); _sage_const_0p387 = RealNumber('0.387'); _sage_const_8 = Integer(8); _sage_const_16p4 = RealNumber('16.4'); _sage_const_0p292 = RealNumber('0.292'); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_3p = RealNumber('3.')
from zgsa_nonsym import ZGSA, ZGSA_old
from batchCVP import batchCVPP_cost
from parser import HelpException, parse_all
from utils import st_dev_central_binomial, H, CB2, CB3

def plot_gso(r, *args, **kwds):
    return line([(i, r_,) for i, r_ in enumerate(r)], *args, **kwds)

#Thm. 4.1
def find_beta(d, n, q, st_dev_e, approx_fact=_sage_const_1p0 ):
    minbeta = _sage_const_50  if d<_sage_const_513  else n//_sage_const_2 
    for beta in range(minbeta, d//_sage_const_2 , _sage_const_1 ): #90, 450, 1
        r_log = ZGSA(d, n, q, beta)
        #r_log = ZGSA_old(d, n, q, beta)
        # if beta%32==0:
        #     plot_gso(r_log).save(f"bkz{beta}.png")
        lhs  = _sage_const_0p5 *log(beta)+log(st_dev_e)
        rhs  = r_log[_sage_const_2 *n-beta] + log(approx_fact) #counting from 0
        if lhs < rhs:
            return beta
        #print(beta, lhs.n(), rhs.n())
    return infinity

#core-SVP
def svp_cost(beta, d, alg="BDGL16_real"):
    if alg == "BDGL16_real":
        return _sage_const_0p387 *beta+log(_sage_const_8 *d,_sage_const_2 )+_sage_const_16p4 
    elif alg == "BDGL16_asym":
        return _sage_const_0p292 *beta+log(_sage_const_8 *d,_sage_const_2 )+_sage_const_16p4 
    else:
        print("Unrecognized SVP algorithm")
        return _sage_const_0 

if __name__=="__main__":
    try:
        n, q, kappa, st_dev_e, dist = parse_all()
        dim = _sage_const_2 *n


        # kappa = 45  #max number of guessed coordiantes
        min_rt = infinity
        minTbkz = _sage_const_0 
        minTcvp = _sage_const_0 
        minbeta = _sage_const_0 
        minkappa = _sage_const_0 
        for kappa_ in range(kappa+_sage_const_1 ):
            M_log = kappa_*H(CB3)+_sage_const_1  # number of CVP-targets
            beta = find_beta(dim-kappa_, n-kappa_, q, st_dev_e)
            if beta==infinity: continue
            Tbkz = svp_cost(beta,dim-kappa_)
            _, Tcvp = batchCVPP_cost(beta, M_log, sqrt(_sage_const_4 /_sage_const_3p ), _sage_const_1 )
            min_ = max(Tbkz, Tcvp)
            if min_<min_rt:
                min_rt = min_
                minTbkz = Tbkz
                minTcvp = Tcvp
                minbeta = beta
                minkappa = kappa_
                print(RR(min_rt), RR(minTbkz), RR(minTcvp), minbeta, minkappa)

        print()
        print(f"n={n}, q={q}")
        print(f"Est. cost: {RR(min_rt):.4f}, Cost SVP: {RR(minTbkz):.4f}, Cost CVP: {RR(minTcvp):.4f}, beta: {minbeta}, guessing coords.: {minkappa}")
    except HelpException:
        pass

